### ISSUE TITLE
Ifc support thru https://ifcjs.io/ 

### ISSUE THREAD

**Issue by Isaina** [dubstar-04/Design-Core#132]
Import ifc into dxf with floor plan and floor browser and save floor plans to dxf for editing! With floor manager to navigate thru floors

**Comment by dubstar-04** [comment]
Thanks for the feature request. Currently only planning to import DXF formats

**Comment by Isaina** [comment]
With dxf can you also add block support and define connection point color lines layer in block so when we click on that point after inserting block we draw with that line styleSent using the mobile mail appOn 05.01.2024. at 17:50, Daniel Wood wrote:
                
            
            
                
                    From: "Daniel Wood" ***@***.***>Date: 5 January 2024To: "dubstar-04/Design-Core" ***@***.***>Cc: "Author" ***@***.***>,"Isaina" ***@***.***>Subject: Re: [dubstar-04/Design-Core] Ifc support thru https://ifcjs.io/  (Issue #132)
                
                
Closed #132 as completed.
